name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/agentil/prowjobscraper:latest
    - name: Log on quay.io
      run: docker login -u="${{ secrets.QUAY_USER }}" -p="${{ secrets.QUAY_PWD }}" quay.io
    - name: Push the Docker image
      run: docker push quay.io/agentil/prowjobscraper:latest
